language: ruby
gemfile:
   - test/support/Gemfile

before_script:
  - wget https://get.docker.io/builds/Linux/x86_64/docker-latest -O /tmp/docker
  - chmod u+x /tmp/docker

install:
  - apt-get install docker.io
  - ps -ef

rvm:
  - 1.9.3

script: bundle exec rake foodcritic rubocop tailor
addons:
   code_climate:
      repo_token: 2e06c55df40cc4a9ba84f06815d56b218dfaad5554253444d2415ceec36c8088
