source 'https://rubygems.org'

group :test, :integration do
  gem 'codeclimate-test-reporter', require: nil
  gem 'chefspec'
  gem 'serverspec'
  gem 'coveralls'
end

gem 'rake'
gem 'rubocop'
gem 'foodcritic'
gem 'tailor'
gem 'chef'
