source 'https://rubygems.org'

gem 'codeclimate-test-reporter', group: :test, require: nil
gem 'berkshelf'
gem 'rake'
gem 'rubocop'
gem 'foodcritic'
gem 'tailor'
gem 'test-kitchen'
gem 'kitchen-docker'
